### ISSUE TITLE
cannot load such file -- ruby_vcloud_sdk/xml/wrapper_classes/envelope

### ISSUE THREAD

**Issue by TheGuyDanish** [OpenNebula/addon-vcloud-driver#1]
After installing OpenNebula according to documentation on a fresh Debian 8 machine, as well as the docs of this project, afterwards following the documentation listed in Guide.md, however any attempts at using the onevcloud app reults in this:

```/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ruby_vcloud_sdk/xml/wrapper_classes/envelope (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/ruby_vcloud_sdk-0.7.8/lib/ruby_vcloud_sdk/xml/wrapper_classes.rb:13:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/ruby_vcloud_sdk-0.7.8/lib/ruby_vcloud_sdk.rb:7:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /usr/lib/one/ruby/vcloud_driver.rb:36:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/bin/onevcloud:34:in `<main>'```

Am I missing something here?

**Comment by acolominas** [comment]
Hi @TheGuyDanish ,

Make sure that file "/var/lib/gems/2.1.0/gems/ruby_vcloud_sdk-0.7.8/lib/ruby_vcloud_sdk/xml/wrapper_classes/envelope.rb" exists.
If "envelope.rb" doesn't exist, we have uploaded a new version gem. Download "ruby_vcloud_sdk-0.7.9.gem" and install it. 

Try this and comment how has it gone.
Thanks.

**Comment by acolominas** [comment]
Hi!
We have fixed some bugs in  OpenNebula-vCloud-Driver/5.0/remotes/vmm/vcloud/vcloud_driver.rb 
Please, download it again and copy it to /usr/lib/one/ruby/vcloud_driver.rb
Thanks.

**Comment by TheGuyDanish** [comment]
With the new ruby_cloud_sdk gem the onevcloud application runs just fine, my only problem now is that I'm unable to connect to vCloud. Are there any specific configurations to keep in mind? The command I'm using is (With details removed):

onevcloud hosts --vcloud <vCloud URI Removed> --vuser <vCloud User Removed> --vpass <Pass removed> --vdc <My vCloud VDC>

I get an:

Error getting oned configuration : [SystemConfig] User couldn't be authenticated, aborting call.

Is this a vCloud-related, or an OpenNebula-related error?

**Comment by acolominas** [comment]
Hi,
I think this is a OpenNebula-related error. Make sure that credentials stored in /var/lib/one/.one/one_auth are correct.

**Comment by TheGuyDanish** [comment]
This turned out to be it. I have my vCloud setup imported into OpenNebula now and I'm able to create VMs. Thank you!
